Added full functionality for displaying heroes (single request no endlesslist yet)
Mathreyu/InstagramApp pull request #2
Opened 2016-12-22 22:16 UTC by Mathreyu

- TODO Add RxJava for Retrofit requests
- TODO Create new recyclerview for comics per character
- TODO Manage Dagger 2 (Learn more)

2016-12-23 04:17 UTC, epool requested changes
@Mathreyu you can use `@SerializedName("json_field")` from gson to map and improve the model field names independently of the JSON name.

2016-12-23 04:17 UTC, epool commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/MainActivity.java
> +        context = this;
@Mathreyu why to do this?

2016-12-23 04:17 UTC, epool commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/MainActivity.java
> +                HeroAdapter adapter = new HeroAdapter(heroes, rvHeroes.getContext());
@Mathreyu you can save the context parameter and get it from the parent group view from the get view adapter method

2016-12-23 04:17 UTC, epool commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/MainActivity.java
> +                rvHeroes.setLayoutManager(new LinearLayoutManager(rvHeroes.getContext()));
@Mathreyu why not use`this` instead of rvHeroes.getContext()?

2016-12-23 04:17 UTC, epool commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/util/HeroAdapter.java
> +            heroThumbnail = (CircleImageView) itemView.findViewById(R.id.hero_thumbnail);
@Mathreyu you could use butter knife here too.

2016-12-23 04:17 UTC, epool commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/util/HeroAdapter.java
> +        context = this.getContext();
@Mathreyu avoid to use `this`.getContext() calling local method in Android.

2016-12-23 04:17 UTC, epool commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/util/HeroAdapter.java
> +    private Context context;
@Mathreyu why to hold this context reference since you are using parent.getContext()?

2016-12-23 04:17 UTC, epool commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/util/HeroAdapter.java
>          TextView textView = viewHolder.heroName;
@Mathreyu you could create a bind (Hero hero) method in the holder class for setting the values in the view as a good practice.

2016-12-23 15:25 UTC, Mathreyu commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/MainActivity.java
> +        context = this;
The thing is I was trying to do all this in a utils class in order to leave all this to an independent class, when I moved it here I forgot to remove it haha sorry

2016-12-23 15:26 UTC, Mathreyu commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/MainActivity.java
> +                rvHeroes.setLayoutManager(new LinearLayoutManager(rvHeroes.getContext()));
Same issue, forgot to change it

2016-12-23 15:26 UTC, Mathreyu commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/util/HeroAdapter.java
> +    private Context context;
Will remove it

2016-12-23 15:27 UTC, Mathreyu commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/util/HeroAdapter.java
> +            heroThumbnail = (CircleImageView) itemView.findViewById(R.id.hero_thumbnail);
Yeah, will do

2016-12-23 15:27 UTC, Mathreyu commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/util/HeroAdapter.java
>          TextView textView = viewHolder.heroName;
Sure, will do this. thanks

2016-12-23 18:49 UTC, Mathreyu commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/MainActivity.java
> +                rvHeroes.setLayoutManager(new LinearLayoutManager(rvHeroes.getContext()));
I dont know why this doesnt seem to be applicable in this case, hence I had to provide the view's contexts.

2016-12-23 19:07 UTC, Mathreyu commented on app/src/main/java/com/academy/ramon/marvelcomicviewer/MainActivity.java
> +                HeroAdapter adapter = new HeroAdapter(heroes, rvHeroes.getContext());
I dont fully understand this, you mean: Save the context inside the adapter and then take it from there? Maybe this is why Im getting this error:  E/RecyclerView: No adapter attached; skipping layout Eventhough the app works fine (so far) and the adapter is set properly

2017-01-02 22:27 UTC, epool commented
LGTM 👍

2017-01-02 22:27 UTC, epool approved these changes
LGTM 👍

2017-01-02 22:28 UTC, merged